### ISSUE TITLE
xapsd crashes

### ISSUE THREAD

**Issue by heinlein-support** [st3fan/dovecot-xaps-plugin#16]
Hi Stefan,

first of all -- thanks a lot for your work with xapsd! Looks like this is the only existing solution for iOS push -- great.

We have some heavy loaded systems and there xapsd dies from time to time. Could you help us to debug the reason for that?

We're using Dovecot 2.2.29 and 2.2.31 on Debian 8.8.

root@imap:~# service dovecot-xaps status 
● dovecot-xaps.service - Dovecot XAPS Daemon
   Loaded: loaded (/lib/systemd/system/dovecot-xaps.service; enabled)
   Active: failed (Result: exit-code) since Sa 2017-07-01 17:14:42 CEST; 8min ago
  Process: 118082 ExecStart=/usr/sbin/xapsd -key=/etc/xapsd/key.pem -certificate=/etc/xapsd/certificate.pem -database=/var/lib/xapsd/xapsd.json -socket=/var/run/xapsd/xapsd.sock (code=exited, status=2)
 Main PID: 118082 (code=exited, status=2)

Jul 01 17:14:42 imap xapsd[118082]: main.(*Database).write(0xc42000c400, 0xc420237e88, 0xc420ae1d08)
Jul 01 17:14:42 imap xapsd[118082]: /root/build/dovecot-xaps-daemon/src/cmd/xapsd/database.go:93 +0x62
Jul 01 17:14:42 imap xapsd[118082]: main.(*Database).addRegistration(0xc42000c400, 0xc420ad80c9, 0x1a, 0xc420ad8019, ...2, ...)
Jul 01 17:14:42 imap xapsd[118082]: /root/build/dovecot-xaps-daemon/src/cmd/xapsd/database.go:115 +0x232
Jul 01 17:14:42 imap xapsd[118082]: main.handleRegister(0x6f2ce0, 0xc420ac8000, 0xc420ad8000, 0x8, 0xc420ad4030, 0xc4..., 0x3b)
Jul 01 17:14:42 imap xapsd[118082]: /root/build/dovecot-xaps-daemon/src/cmd/xapsd/xapsd.go:303 +0x2f7
Jul 01 17:14:42 imap xapsd[118082]: main.handleRequest(0x6f2ce0, 0xc420ac8000, 0xc42015f640, 0xc42000c400, 0xc420144fc0, 0x3b)
Jul 01 17:14:42 imap xapsd[118082]: /root/build/dovecot-xaps-daemon/src/cmd/xapsd/xapsd.go:242 +0x388
Jul 01 17:14:42 imap xapsd[118082]: created by main.main
Jul 01 17:14:42 imap xapsd[118082]: /root/build/dovecot-xaps-daemon/src/cmd/xapsd/xapsd.go:222 +0x498
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by freswa** [comment]
@heinlein-support Which go version do you use? Could you please provide the log until xapsd crashes?

**Comment by heinlein-support** [comment]
We're always use the latest version from Github.

There's nothing special in the logfiles. xapsd is gone, there's no reason or famous last words....

root@mail:~# grep xaps /var/log/mail | grep 17:5
                                                                                                               
```
Sep  4 17:59:59 mail dovecot: imap(user1@example.org): Error: read(/var/run/xapsd/xapsd.sock) failed: Success
Sep  4 17:59:59 mail dovecot: imap(user1@example.org): Error: read(/var/run/xapsd/xapsd.sock) failed: Success
```

`Sep  4 17:59:59 mail dovecot: imap(user2@example.org): Error: read(/var/run/xapsd/xapsd.sock) failed: Connection reset by peer`

and then multiple times

`Sep  4 17:59:59 mail dovecot: lmtp(user3@example.org): Error: net_connect_unix(/var/run/xapsd/xapsd.sock) failed: Connection refused
`
 until our systemd has restarted xapsd:

```
Sep 04 17:59:59 mail systemd[1]: Started Dovecot XAPS Daemon.
Sep 04 18:00:00 mail xapsd[120429]: 2017/09/04 18:00:00 Starting xapsd 1.0b1 on /var/run/xapsd/xapsd.sock
```

**Comment by freswa** [comment]
@heinlein-support Ok, that's the plugin log. Could you please paste the xapsd log?

**Comment by heinlein-support** [comment]
Oh shit. How stupid I am. You got me. I'm in linux for ~25 years every day and I haven't seen that there's xapsd log in daemon.log (which i normally never use...). Sorry, sorry, sorry. I'm soooo stupid.

Yes, there's the reason: "fatal error: concurrent map writes" which means, that xapsd already understood that problem, but still was not able to handle it. 

But even then, a "drop the request" would be better then "kill the daemon"...

I can't grep "map writes" at all in the code -- so maybe that's something coming out of xaps from a go library?

```
 xapsd[3144]: fatal error: concurrent map writes
 xapsd[3144]: goroutine 48203 [running]:
 xapsd[3144]: runtime.throw(0x61d916, 0x15)
 xapsd[3144]: /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4206ccc00 sp=0xc4206ccbe0
 xapsd[3144]: runtime.mapassign(0x5e3920, 0xc4202600c0, 0xc4206cccd8, 0x16)
 xapsd[3144]: /usr/local/go/src/runtime/hashmap.go:499 +0x667 fp=0xc4206ccca0 sp=0xc4206ccc00
 xapsd[3144]: main.(*Database).addRegistration(0xc42000c3e0, 0xc4218e92c9, 0x16, 0xc4218e9219, 0x24, 0xc4218e9251, 0x40, 0xc4204f9440, 0x3, 0x4, ...)
 xapsd[3144]: /root/build/dovecot-xaps-daemon/src/cmd/xapsd/database.go:113 +0x1ec fp=0xc4206ccd68 sp=0xc4206ccca0
 xapsd[3144]: main.handleRegister(0x6f2ce0, 0xc42000e120, 0xc4218e9200, 0x8, 0xc42021c900, 0xc420673dc0, 0xc42000c3e0, 0xc420676880, 0x3b)
 xapsd[3144]: /root/build/dovecot-xaps-daemon/src/cmd/xapsd/xapsd.go:303 +0x2f7 fp=0xc4206cce08 sp=0xc4206ccd68
 xapsd[3144]: main.handleRequest(0x6f2ce0, 0xc42000e120, 0xc420673dc0, 0xc42000c3e0, 0xc420676880, 0x3b)
 xapsd[3144]: /root/build/dovecot-xaps-daemon/src/cmd/xapsd/xapsd.go:242 +0x388 fp=0xc4206ccfb0 sp=0xc4206cce08
 xapsd[3144]: runtime.goexit()
 xapsd[3144]: /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4206ccfb8 sp=0xc4206ccfb0
 xapsd[3144]: created by main.main
 xapsd[3144]: /root/build/dovecot-xaps-daemon/src/cmd/xapsd/xapsd.go:222 +0x498
 xapsd[3144]: goroutine 1 [IO wait]:
 xapsd[3144]: net.runtime_pollWait(0x7f8bc168d7c0, 0x72, 0x6ef520)
 xapsd[3144]: /usr/local/go/src/runtime/netpoll.go:164 +0x59
 xapsd[3144]: net.(*pollDesc).wait(0xc420062068, 0x72, 0x6ed3c8, 0xc4201bf880)
 xapsd[3144]: /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
 xapsd[3144]: net.(*pollDesc).waitRead(0xc420062068, 0xffffffffffffffff, 0x0)
 xapsd[3144]: /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
 xapsd[3144]: net.(*netFD).accept(0xc420062000, 0x0, 0x6eed60, 0xc4201bf880)
 xapsd[3144]: /usr/local/go/src/net/fd_unix.go:430 +0x1e5
 xapsd[3144]: net.(*UnixListener).accept(0xc4206784e0, 0xc4206b1b10, 0x5b1078, 0x451ef0)
 xapsd[3144]: /usr/local/go/src/net/unixsock_posix.go:162 +0x32
 xapsd[3144]: net.(*UnixListener).Accept(0xc4206784e0, 0x626c68, 0x6f2ce0, 0xc42000e120, 0xc420673dc0)
 xapsd[3144]: /usr/local/go/src/net/unixsock.go:237 +0x49
 xapsd[3144]: main.main()
 xapsd[3144]: /root/build/dovecot-xaps-daemon/src/cmd/xapsd/xapsd.go:212 +0x40d
 xapsd[3144]: goroutine 17 [syscall, 76 minutes, locked to thread]:
 xapsd[3144]: runtime.goexit()
 xapsd[3144]: /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
 xapsd[3144]: goroutine 36 [select]:
 xapsd[3144]: github.com/st3fan/apns.(*Client).runLoop(0xc4206991e0)
 xapsd[3144]: /root/build/dovecot-xaps-daemon/vendor/src/github.com/st3fan/apns/client.go:153 +0x65a
 xapsd[3144]: created by github.com/st3fan/apns.newClientWithConn
 xapsd[3144]: /root/build/dovecot-xaps-daemon/vendor/src/github.com/st3fan/apns/client.go:46 +0x11b
 xapsd[3144]: goroutine 37 [chan receive, 76 minutes]:
 xapsd[3144]: main.main.func1(0xc420673dc0)
 xapsd[3144]: /root/build/dovecot-xaps-daemon/src/cmd/xapsd/xapsd.go:204 +0xb2
 xapsd[3144]: created by main.main
 xapsd[3144]: /root/build/dovecot-xaps-daemon/src/cmd/xapsd/xapsd.go:207 +0x307
 xapsd[3144]: goroutine 20 [IO wait, 76 minutes]:
 xapsd[3144]: net.runtime_pollWait(0x7f8bc168d700, 0x72, 0x5)
 xapsd[3144]: /usr/local/go/src/runtime/netpoll.go:164 +0x59
 xapsd[3144]: net.(*pollDesc).wait(0xc420062538, 0x72, 0x6ef520, 0x6ed3c8)
 xapsd[3144]: /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
 xapsd[3144]: net.(*pollDesc).waitRead(0xc420062538, 0xc420481400, 0x400)
 xapsd[3144]: /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
 xapsd[3144]: net.(*netFD).Read(0xc4200624d0, 0xc420481400, 0x400, 0x400, 0x0, 0x6ef520, 0x6ed3c8)
 xapsd[3144]: /usr/local/go/src/net/fd_unix.go:250 +0x1b7
 xapsd[3144]: net.(*conn).Read(0xc4206ac050, 0xc420481400, 0x400, 0x400, 0x0, 0x0, 0x0)
 xapsd[3144]: /usr/local/go/src/net/net.go:181 +0x70
 xapsd[3144]: crypto/tls.(*block).readFromUntil(0xc420440ff0, 0x7f8bc161e078, 0xc4206ac050, 0x5, 0xc4206ac050, 0x5d5680)
 xapsd[3144]: /usr/local/go/src/crypto/tls/conn.go:488 +0x98
 xapsd[3144]: crypto/tls.(*Conn).readRecord(0xc420098380, 0x627217, 0xc4200984a0, 0x0)
 xapsd[3144]: /usr/local/go/src/crypto/tls/conn.go:590 +0xc4
 xapsd[3144]: crypto/tls.(*Conn).Read(0xc420098380, 0xc420686000, 0x6, 0x6, 0x0, 0x0, 0x0)
 xapsd[3144]: /usr/local/go/src/crypto/tls/conn.go:1134 +0x11d
 xapsd[3144]: github.com/st3fan/apns.(*Conn).Read(0xc420678c90, 0xc420686000, 0x6, 0x6, 0x6, 0x6, 0x0)
 xapsd[3144]: /root/build/dovecot-xaps-daemon/vendor/src/github.com/st3fan/apns/conn.go:88 +0x51
 xapsd[3144]: github.com/st3fan/apns.readErrs.func1(0xc420678c90, 0xc4206d4060)
 xapsd[3144]: /root/build/dovecot-xaps-daemon/vendor/src/github.com/st3fan/apns/client.go:208 +0x84
 xapsd[3144]: created by github.com/st3fan/apns.readErrs
 xapsd[3144]: /root/build/dovecot-xaps-daemon/vendor/src/github.com/st3fan/apns/client.go:216 +0x67
 xapsd[3144]: goroutine 48202 [runnable]:
 xapsd[3144]: reflect.unsafe_New(0x5d54c0, 0xc4205a1558)
 xapsd[3144]: /usr/local/go/src/runtime/malloc.go:812 +0x44
 xapsd[3144]: reflect.Value.MapKeys(0x5e3980, 0xc42000c3f0, 0x195, 0x0, 0x1022, 0x1022)
 xapsd[3144]: /usr/local/go/src/reflect/value.go:1106 +0x27c
 xapsd[3144]: encoding/json.(*mapEncoder).encode(0xc42000e100, 0xc420696160, 0x5e3980, 0xc42000c3f0, 0x195, 0x100)
 xapsd[3144]: /usr/local/go/src/encoding/json/encode.go:674 +0xad
 xapsd[3144]: encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc420696160, 0x5e3980, 0xc42000c3f0, 0x195, 0x100)
 xapsd[3144]: /usr/local/go/src/encoding/json/encode.go:706 +0x64
 xapsd[3144]: encoding/json.(*structEncoder).encode(0xc42062eab0, 0xc420696160, 0x5f14e0, 0xc42000c3e0, 0x199, 0x100)
 xapsd[3144]: /usr/local/go/src/encoding/json/encode.go:645 +0x253
 xapsd[3144]: encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc420696160, 0x5f14e0, 0xc42000c3e0, 0x199, 0xc420000100)
 xapsd[3144]: /usr/local/go/src/encoding/json/encode.go:659 +0x64
 xapsd[3144]: encoding/json.(*ptrEncoder).encode(0xc42000e108, 0xc420696160, 0x5ea060, 0xc42000c3e0, 0x16, 0x5e0100)
 xapsd[3144]: /usr/local/go/src/encoding/json/encode.go:786 +0xe3
 xapsd[3144]: encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc420696160, 0x5ea060, 0xc42000c3e0, 0x16, 0xc420000100)
 xapsd[3144]: /usr/local/go/src/encoding/json/encode.go:791 +0x64
 xapsd[3144]: encoding/json.(*encodeState).reflectValue(0xc420696160, 0x5ea060, 0xc42000c3e0, 0x16, 0x100)
 xapsd[3144]: /usr/local/go/src/encoding/json/encode.go:323 +0x82
 xapsd[3144]: encoding/json.(*encodeState).marshal(0xc420696160, 0x5ea060, 0xc42000c3e0, 0xc4204d0100, 0x0, 0x0)
 xapsd[3144]: /usr/local/go/src/encoding/json/encode.go:296 +0xb8
 xapsd[3144]: encoding/json.Marshal(0x5ea060, 0xc42000c3e0, 0xc42025cf18, 0xc4206cdcd8, 0x10, 0x24, 0x7f8bc16cd701)
 xapsd[3144]: /usr/local/go/src/encoding/json/encode.go:161 +0x6e
 xapsd[3144]: encoding/json.MarshalIndent(0x5ea060, 0xc42000c3e0, 0x0, 0x0, 0x619e38, 0x2, 0x0, 0xc42025cf00, 0x708290, 0xc4205af7e0, ...)
 xapsd[3144]: /usr/local/go/src/encoding/json/encode.go:170 +0x3f
 xapsd[3144]: main.(*Database).write(0xc42000c3e0, 0xc4202600c0, 0xc4206cdcd8)
 xapsd[3144]: /root/build/dovecot-xaps-daemon/src/cmd/xapsd/database.go:93 +0x62
 xapsd[3144]: main.(*Database).addRegistration(0xc42000c3e0, 0xc4218e40c9, 0x16, 0xc4218e4019, 0x24, 0xc4218e4051, 0x40, 0xc4204dd240, 0x3, 0x4, ...)
 xapsd[3144]: /root/build/dovecot-xaps-daemon/src/cmd/xapsd/database.go:115 +0x232
 xapsd[3144]: main.handleRegister(0x6f2ce0, 0xc42000e118, 0xc4218e4000, 0x8, 0xc42071a000, 0xc420673dc0, 0xc42000c3e0, 0xc420676880, 0x3b)
 xapsd[3144]: /root/build/dovecot-xaps-daemon/src/cmd/xapsd/xapsd.go:303 +0x2f7
 xapsd[3144]: main.handleRequest(0x6f2ce0, 0xc42000e118, 0xc420673dc0, 0xc42000c3e0, 0xc420676880, 0x3b)
 xapsd[3144]: /root/build/dovecot-xaps-daemon/src/cmd/xapsd/xapsd.go:242 +0x388
 xapsd[3144]: created by main.main
 xapsd[3144]: /root/build/dovecot-xaps-daemon/src/cmd/xapsd/xapsd.go:222 +0x498
 systemd[1]: dovecot-xaps.service: main process exited, code=exited, status=2/INVALIDARGUMENT
 systemd[1]: Unit dovecot-xaps.service entered failed state.
 systemd[1]: dovecot-xaps.service holdoff time over, scheduling restart.

```

**Comment by freswa** [comment]
Thanks alot. So the problem seems pretty clear to me. There are two people registering simultaneously. The subsequent write of the json to the fs is not protected via mutex, so the write fails and the daemon crashes.

**Comment by heinlein-support** [comment]
Yes, reading the logfile the problem is immediately clear. But now I need someone able to code/fix it in GO...
