### ISSUE TITLE
dovecot crash with this email

### ISSUE THREAD

**Issue by pelletierr** [st3fan/dovecot-xaps-plugin#46]
Since version 2.3.9, certain mail makes lmtp and imap processes crash.
I made shure I had the latest plugin version and recompiled it.

Attached is the anonymized source of the message <removed>

**Comment by freswa** [comment]
Could you try to revert the following commits of dovecot core and try again?
e279c891d92f06feb1682530f3b55f4f80972852
1256df390370c1bddca02252425e5e4eb42dfa02
be5e2c6ca0a527ebfb080a546a2891c1b86c2bf7

**Comment by pelletierr** [comment]
Sorry, I am using Dovecot's CentOS repository. I am not compiling it myself.
I could send you a test message if you wish, I can recreate the problem quickly.

**Comment by freswa** [comment]
Could you create a crashdump and paste the stackstrace here?

**Comment by pelletierr** [comment]
segfault at 0 ip 00007fa1c370ecea sp 00007ffd1ce39be0 error 4 in lib20_push_notification_plugin.so[7fa1c3708000+c000]

Core dump attached <removed>

**Comment by freswa** [comment]
Could you paste the stacktrace? Just open the dump in gdb `gdb /usr/lib/dovecot/imap <coredump>` and type `where`

**Comment by pelletierr** [comment]
```
#0  0x00007f456a7b0cea in decode_address_header ()
   from /usr/lib64/dovecot/lib20_push_notification_plugin.so
#1  0x00007f456a7b0fdf in push_notification_message_fill ()
   from /usr/lib64/dovecot/lib20_push_notification_plugin.so
#2  0x00007f456a7b0aed in push_notification_event_messagenew_event ()
   from /usr/lib64/dovecot/lib20_push_notification_plugin.so
#3  0x00007f456a7b226d in push_notification_trigger_msg_save_new ()
   from /usr/lib64/dovecot/lib20_push_notification_plugin.so
#4  0x00007f456abf6383 in notify_contexts_mail_save ()
   from /usr/lib64/dovecot/lib15_notify_plugin.so
#5  0x00007f456abf76c2 in notify_copy ()
   from /usr/lib64/dovecot/lib15_notify_plugin.so
#6  0x00007f456ae099c4 in quota_copy ()
   from /usr/lib64/dovecot/lib10_quota_plugin.so
#7  0x00007f456db0d072 in mailbox_copy_int ()
   from /usr/lib64/dovecot/libdovecot-storage.so.0
#8  0x00007f45688fbfcb in act_store_execute ()
   from /usr/lib64/dovecot/libdovecot-sieve.so.0
#9  0x00007f45688f1617 in _sieve_result_implicit_keep ()
   from /usr/lib64/dovecot/libdovecot-sieve.so.0
#10 0x00007f45688f211b in sieve_result_implicit_keep ()
   from /usr/lib64/dovecot/libdovecot-sieve.so.0
#11 0x00007f4568905401 in sieve_multiscript_finish ()
   from /usr/lib64/dovecot/libdovecot-sieve.so.0
#12 0x00007f4568b7183e in lda_sieve_deliver_mail ()
   from /usr/lib64/dovecot/lib90_sieve_plugin.so
#13 0x00007f456de1e993 in mail_deliver ()
   from /usr/lib64/dovecot/libdovecot-lda.so.0
#14 0x00005575d96fb204 in lmtp_local_default_deliver ()
#15 0x00005575d96fb8e3 in lmtp_local_data ()
#16 0x00005575d96fa1fb in client_default_cmd_data ()
#17 0x00005575d96f9f8a in cmd_data_continue ()
#18 0x00007f456d774eb7 in cmd_data_handle_input ()
   from /usr/lib64/dovecot/libdovecot.so.0
#19 0x00007f456d81c95f in io_loop_call_io ()
   from /usr/lib64/dovecot/libdovecot.so.0
#20 0x00007f456d81e3c3 in io_loop_handler_run_internal ()
   from /usr/lib64/dovecot/libdovecot.so.0
#21 0x00007f456d81ca69 in io_loop_handler_run ()
   from /usr/lib64/dovecot/libdovecot.so.0
#22 0x00007f456d81cca8 in io_loop_run ()
   from /usr/lib64/dovecot/libdovecot.so.0
#23 0x00007f456d78cd63 in master_service_run ()
   from /usr/lib64/dovecot/libdovecot.so.0
#24 0x00005575d96f8b96 in main ()

**Comment by freswa** [comment]
Reported upstream. WIP

**Comment by pelletierr** [comment]
Thank you!

**Comment by freswa** [comment]
Should be fixed with dovecot 2.3.9.1

**Comment by pelletierr** [comment]
Confirmed working! Thank you very much!

**Comment by freswa** [comment]
2.3.9.2 has just been released fixing a similar issue with empty To/From header...
